version: '2'
services:    
  spark-master:
    build: .
    container_name: spark-master
    entrypoint: /opt/bootstrap-master.sh
    image: spark-master:2.1
    volumes:
      - data-volume:/var/data
    
  spark-slave:
    build: .
    image: spark-slave:2.1
    entrypoint: /opt/bootstrap-slave.sh
    depends_on:
      - spark-master
    volumes:
      - data-volume:/var/data
        
volumes:
  data-volume: