version: '2'
services:    
  spark-master:
    build: .
    container_name: spark-master
    entrypoint: /opt/bootstrap-master.sh
    
  spark-worker1:
    build: .
    entrypoint: /opt/bootstrap-slave.sh
    depends_on:
      - spark-master
      
  spark-worker2:
    build: .
    entrypoint: /opt/bootstrap-slave.sh
    depends_on:
      - spark-master
