version: '2'
services:    
  spark-master:
    container_name: spark-master
    image: dawidnowak/spark-standalone:2.1
    environment:
      SPARK_MODE: master
    volumes:
      - data-volume:/var/spark_data
    
  spark-node:
    image: dawidnowak/spark-standalone:2.1
    depends_on:
      - spark-master
    volumes:
      - data-volume:/var/spark_data
        
volumes:
  data-volume: